---
version: '3'

services:
  tinytuya2mqtt:
    image: ghcr.io/mafrosis/tinytuya2mqtt:dev
    restart: unless-stopped
    build:
      context: .
    environment:
      - DEBUG
    volumes:
      - ./snapshot.json:/snapshot.json:ro
      - ./tinytuya2mqtt.ini:/tinytuya2mqtt.ini:ro

  test:
    image: mafrosis/tinytuya2mqtt:test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./snapshot.json:/snapshot.json:ro
      - ./tinytuya2mqtt.ini:/tinytuya2mqtt.ini:ro
      - ./tinytuya2mqtt:/src/tinytuya2mqtt
